### ISSUE TITLE
Unable to upload 18GB file with latest build, just hangs

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#104]
Was able to download an 18GB file successfully.
Tried to upload same file to new collection, but upload just hangs
Checking "details" shows that transfer completed 0 our of 0 files in 1 attempt
Refreshing the window shows a zero byte file uploaded.

This was with v2.0.1-RC1 from:
https://github.com/DICE-UNC/idrop/wiki/iDrop-Installers
![screen shot 2015-02-11 at 7 39 40 am](https://cloud.githubusercontent.com/assets/636374/6148989/bed120a4-b1c2-11e4-9d08-56383cf60b8f.png)

![screen shot 2015-02-11 at 7 53 06 am](https://cloud.githubusercontent.com/assets/636374/6149036/10c6a7a8-b1c3-11e4-9d9e-e28f6814a0d1.png)

I was able to complete an iput & iget from same machine

**Comment by michael-conway** [comment]
Hey jerry it shows the status as 'processing'?

Did it error out, or is it still ongoing?

What is the time-out setting under settings, pipeline configuration, agent
timeout?

Cheers
MC

**Comment by jerry57** [comment]
Timeout was set to "0" by default.

Process never completed, just appeared to be hung, progressbar never 
moved.  I had to end session and reopen iDrop

jer

On 2/11/15 8:05 AM, Mike Conway wrote:
> Hey jerry it shows the status as 'processing'?
>
> Did it error out, or is it still ongoing?
>
> What is the time-out setting under settings, pipeline configuration, agent
> timeout?
>
> Cheers
> MC
>
>
> On Wed, Feb 11, 2015 at 9:53 AM, Jerry Schneider 
> <notifications@github.com>
> wrote:
>
> > Was able to download an 18GB file successfully.
> > Tried to upload same file to new collection, but upload just hangs
> > Checking "details" shows that transfer completed 0 our of 0 files in 1
> > attempt
> >
> > This was with v2.0.1-RC1 from:
> > https://github.com/DICE-UNC/idrop/wiki/iDrop-Installers
> > [image: screen shot 2015-02-11 at 7 39 40 am]
> > 
> <https://cloud.githubusercontent.com/assets/636374/6148989/bed120a4-b1c2-11e4-9d08-56383cf60b8f.png>
> >
> > [image: screen shot 2015-02-11 at 7 53 06 am]
> > 
> <https://cloud.githubusercontent.com/assets/636374/6149036/10c6a7a8-b1c3-11e4-9d9e-e28f6814a0d1.png>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DICE-UNC/idrop/issues/104>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DICE-UNC/idrop/issues/104#issuecomment-73895552>.
>

-- 
Linux registered user #475536
Ubuntu registered user #28583

**Comment by michael-conway** [comment]
Hey Jerry, it might not have been hung.  After completion, it's trying to
compute a checksum on the iRODS side.  That could be one issue.  I would be
interested to see if iRODS presents any errors?  Is the file there in
iRODS?  I can see the same sort of thing when I did my 14 gb upload, it
shows complete, then it hangs for a good bit, but it ultimately succeeded
after the checksum was computed.

Second, it could be a legit network connection timeout issue.  The
connection tester was successful?

**Comment by jerry57** [comment]
I just tried this from a Windows 8.1 x64 install for same user
The upload has been running for more than 10 min now and not progressed at all.
Details show it as "complete with a few warnings but file is zero bytes in size on server

here a a screenshot of the Virtualbox Machine windows:
![screen shot 2015-02-11 at 8 26 31 am](https://cloud.githubusercontent.com/assets/636374/6149749/329ee61a-b1c8-11e4-9668-8a76f1939316.png)

**Comment by michael-conway** [comment]
OK.

I think it's a legit network error, the next step is to test w/ipc

**Comment by michael-conway** [comment]
Hey Jerry,

I think the bottom like is that this is wrapped up in network time-outs 
at some layer.  I'm working through this but there are several pieces to it.

1) can you test this with iput and see what happens?

2) since we set the time-out to 0 in iDrop, I saw something here in the 
test lab where the parallel transfer threads would eventually time out 
(they do have, by default, a 120 second time out on the parallel 
connections).  When this happens, iDrop was trying to send an 
'operationComplete' message, which, since the 1247 connection was set to 
0 for timeouts, would never time out.  Thus iDrop appears 'hung' in a 
processing state.  I bet this is part of what Nicolle saw.


Sooo...I am first adding a feature to jargon where, even thought the 
timeout on 1247 can be set to zero for no time out, I can set a special 
value in jargon.properties that says 'watch the operation complete 
call', and use a separate timer thread to do a time out. This at least 
allows no time outs on the iRODS socket, but no perpetual clocking in 
the client.  I want to see what that does.

If iPut succeeds, that's a good data point, I think it will fail but I'm 
not a great guesser.  I think I need to press ahead to add long file 
restarts into Jargon, and it could be that we let these things time out, 
and do an automatic recovery and restart in those cases. I'll start 
looking at that.

But having some data points will help, I think it's actually just a 
complicated end-to-end problem, but not impossible to solve.

MC

**Comment by jerry57** [comment]
Mike, in the original writeup, I stated that I was able to do an iput and and iget of the same file from the same client machine.

**Comment by jerry57** [comment]
Tried this with build v2.0.1-RC1-003.  Download hung after 17 (actually 18GB) file.  I waited more than 30min for completion and then just ended up killing iDrop.

![screen shot 2015-02-24 at 10 46 56 am](https://cloud.githubusercontent.com/assets/636374/6355340/8d384c5c-bc12-11e4-8186-2e312efc48c6.png)
